#!/bin/sh
## Adaptation Grassland in Lucheng 2018.12.11

ad_home="/etc/storage/adb"

echo -e -n "\033[41;37m 开始构建 Adbyby 启动文件......\033[0m\n"
sleep 3
if [ ! -d "$ad_home" ]; then
	echo -e "\e[1;36m 创建 'Adbyby' 文件夹 \e[0m\n"
	mkdir -p -m 777 "$ad_home"
fi

if [ ! -f "$ad_home/bin/adbyby" ]; then
	logger -t "adbyby" "adbyby 程序文件不存在,准备下载..."
	wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/7620n.tar.gz -O /tmp/7620n.tar.gz && sleep 2
	wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/ad_up -O /tmp/tmp_ad_up
	sleep 2 && mv -f /tmp/tmp_ad_up $ad_home/ad_up && chmod 755 $ad_home/ad_up
	wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/ad_whost -O /tmp/tmp_ad_whost
	sleep 2 && mv -f /tmp/tmp_ad_whost $ad_home/ad_whost && chmod 755 $ad_home/ad_whost
	wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/ad_stop -O /tmp/tmp_ad_stop
	sleep 2 && mv -f /tmp/tmp_ad_stop $ad_home/ad_stop && chmod 755 $ad_home/ad_stop
	wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/adbyby.sh -O /tmp/tmp_adbyby.sh
	sleep 2 && mv -f /tmp/tmp_adbyby.sh $ad_home/adbyby.sh && chmod 755 $ad_home/adbyby.sh
	sleep 2 && tar -xzf "/tmp/7620n.tar.gz" -C "$ad_home"
	sleep 2 && $ad_home/ad_up
	echo -e "\e[1;34m adbyby 下载完成并成功解压文件 \e[0m\n" && sleep 3
else
	if [ -f "$ad_home/adbyby.sh" ]; then
		logger -t "adbyby" "adbyby 开始启动"
	else
		wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/adbyby.sh -O /tmp/tmp_adbyby.sh
		cp -f /tmp/tmp_adbyby.sh "$ad_home/adbyby.sh"	
	fi
	sleep 3 && sh $ad_home/bin/adbyby.sh
	echo -e "\e[1;34m 开始运行 adbyby 启动文件 \e[0m\n" && sleep 3
fi
sleep 3 && [ -f /tmp/tmp_ad_stop ] rm -f /tmp/tmp_ad_stop; [ -f /tmp/tmp_ad_up ] rm -f /tmp/tmp_ad_up; [ -f /tmp/tmp_ad_whost ] rm -f /tmp/tmp_ad_whost
[ -f /tmp/7620n.tar.gz ] rm -f /tmp/7620n.tar.gz; [ -f /tmp/tmp_ad_an ] rm -f /tmp/tmp_ad_an; [ -f /tmp/adbyby.sh ] rm -f /tmp/tmp_adbyby.sh
sleep 3 && exit 0
