#!/bin/sh
## Adaptation Grassland in Lucheng 2018.12.11

ad_home="/etc/storage/adb"
ad_start="$ad_home/adbyby.sh"

echo -e -n "\033[41;37m 开始构建 Adbyby 启动文件......\033[0m\n"
sleep 3
if [ ! -d "$ad_home" ]; then
	echo -e "\e[1;36m 创建 'Adbyby' 文件夹 \e[0m\n"
	mkdir -p -m 777 "$ad_home"
fi

if [ ! -f "$ad_home/bin/adbyby" ]; then
	logger -t "adbyby" "adbyby 程序文件不存在,准备下载..."
	wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/7620n.tar.gz -O /tmp/7620n.tar.gz && sleep 2
	tar -xzf "/tmp/7620n.tar.gz" -C "$ad_home"
	echo -e "\e[1;34m adbyby 下载完成并成功解压文件 \e[0m\n" && sleep 3
else
	if [ -f "$ad_start" ]; then
		logger -t "adbyby" "adbyby 开始启动"
	else
		wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/adbyby.sh -O /tmp/tmp_adbyby.sh
		cp -f /tmp/tmp_adbyby.sh "$ad_start"	
	fi
	[ -f /tmp/tmp_adbyby.sh ] && rm -f /tmp/tmp_adbyby.sh;sleep 3 && sh "$ad_start"
	echo -e "\e[1;34m 开始运行 adbyby 启动文件 \e[0m\n" && sleep 3
fi
