#!/bin/sh
## Adaptation Grassland in Lucheng 2019.01.05

echo -e "*****************************************************"
echo -e "\e[1;31m     Adbyby 7620n PADAVAN \e[0m"
echo -e "*****************************************************\n"

echo -e "\e[1;33m >	1. 安装 \e[1;33mpadavan \033[41;37m Adbyby_7620n \e[0m\n"

echo -e "\e[1;32m >	2. 更新 \e[1;36mpadavan \033[44;37m Adbyby 规则 \e[0m\n"

echo -e "\e[1;31m >	3. 卸载 \e[1;36mpadavan	Adbyby_7620n \e[0m\n"

echo -e "\e[1;33m >	4. 安装 \e[1;33mpadavan \033[44;37m HSOSTS 广告屏蔽脚本 \e[0m\n"

echo -e "\e[1;31m >	5. 卸载 \e[1;36mpadavan	HSOSTS 广告屏蔽脚本\e[0m\n"

echo -e "\e[1;33m >	6. 安装 \e[1;33mpadavan \033[45;37m 创建 Dns 环境 \e[0m\n"

echo -e "\e[1;31m >	7. 卸载 \e[1;36mpadavan	恢复 Dns 环境 \e[0m\n"

echo -e "\e[1;33m >	8. 增强 \e[1;33mpadavan \033[45;37m 防火墙规则 \e[0m\n"

echo -e "\e[1;31m >	0. \033[41;37m退出\e[0m\n"

echo -e -n "\e[44;37m 请输入数字继续执行: \e[0m" 
read Function_options
if [ "$Function_options" == "1" ]; then
	if [ ! -d "/tmp/ad_an" ]; then
		if [ -f "/tmp/ad_an" ]; then
			echo -e "\e[1;34m Adbyby 安装完成;开始运行 \e[0m\n" && sleep 3
		else
			echo -e "\e[1;34m 下载 Adbyby 脚本安装 \e[0m\n"
			wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/ad_an -O /tmp/ad_an && sleep 2
		fi
		chmod 777 /tmp/ad_an; sh /tmp/ad_an
		[ -f /tmp/ad_an ] && rm -f /tmp/ad_an; sleep 6 && sh /tmp/Ad_Install
	else
		chmod 777 /tmp/ad_an;sh /tmp/ad_an
		echo -e "\e[1;34m 安装完成,开始运行 \e[0m\n" && logger " Adbyby 安装完成,开始运行..." && sleep 3
		[ -f /tmp/ad_an ] && rm -f /tmp/ad_an; sleep 6 && sh /tmp/Ad_Install
	fi
fi

if [ "$Function_options" == "2" ]; then
	if [ ! -f /tmp/adb/ad_up ]; then
		echo -e "\e[1;34m 没有发现 Ad_up,开始下载更新文件 \e[0m\n" && sleep 3
		wget --no-check-certificate -t 15 -T 50 https://raw.githubusercontent.com/896660689/AD/master/file/ad_up -O /tmp/ad_up && sleep 2
		sh /tmp/ad_up
	else
		sh /tmp/adb/ad_up
		echo -e "\e[1;34m 更新已完成,返回主菜单 \e[0m\n" && logger " Adbyby 更新已完成..." && sleep 3
	fi
	[ -f /tmp/ad_up ] && rm -f /tmp/ad_up; sleep 3 && sh /tmp/Ad_Install
fi

if [ "$Function_options" == "3" ]; then
	if [ ! -f /tmp/adb/ad_stop ]; then
		echo -e "\e[1;34m 没有发现卸载文件,开始下载 \e[0m\n" && logger " Adbyby 卸载已完成..."  && sleep 3
		wget --no-check-certificate https://raw.githubusercontent.com/896660689/AD/master/file/ad_stop -O /tmp/tmp_ad_stop && sleep 2
		chmod 777 /tmp/tmp_ad_stop; sh /tmp/tmp_ad_stop
	else
		chmod 777 /tmp/adb/ad_stop; sh /tmp/adb/ad_stop
		echo -e "\e[1;34m 卸载已完成,返回主菜单 \e[0m\n" && logger " Adbyby 卸载已完成..." && sleep 3
	fi
	[ -f /tmp/tmp_ad_stop ] && rm -f /tmp/tmp_ad_stop; sleep 3 && sh /tmp/Ad_Install
fi

if [ "$Function_options" == "4" ]; then
	[ -f /tmp/hsfq_script.sh ] && rm -rf /tmp/hsfq_script.sh
	wget --no-check-certificate https://raw.githubusercontent.com/896660689/AD/master/Other/Hs_ad -O \
	/tmp/hsfq_ssad.sh && chmod +x /tmp/hsfq_ssad.sh && sh /tmp/hsfq_ssad.sh
	echo -e "\e[1;34m HSOSTS 广告屏蔽脚本配置完成，返回主菜单 \e[0m\n" && logger " HSOSTS 广告屏蔽脚本配置完成..." && sleep 3 
	sh /tmp/Ad_Install
fi

if [ "$Function_options" == "5" ]; then
	if [ -f "/etc/storage/dnsmasq/dnsmasq.conf" ]; then
		echo -e "\e[1;31m 开始卸载启动规则 \e[0m\n"
		sed -i '/addn-hosts/d' /etc/storage/dnsmasq/dnsmasq.conf
	fi

	if [ -f "/etc/storage/cron/crontabs/$username" ]; then
		echo -e "\e[1;31m 删除更新计划任务 \e[0m\n" && sleep 2
		sed -i '/hsfq_ssad/d' /etc/storage/cron/crontabs/$username
		killall crond;/usr/sbin/crond
	fi

	if [ -d "/etc/storage/bin/hosts" ]; then
		echo -e "\e[1;31m 删除残留文件夹以及配置 \e[0m\n" && sleep 2
		rm -rf /etc/storage/bin/hosts
		rm -rf /etc/storage/bin/hsfq_ssad.sh
	fi

	if [ -f "/usr/sbin/dnsmasq" ]; then
		echo -e "\e[1;31m 重启 dnsmasq \e[0m\n"
		restart_dhcpd && /usr/sbin/dnsmasq restart >/dev/null 2>&1
	fi

	[ -f "/tmp/hsfq_ssad.sh" ] && rm -f /tmp/hsfq_ssad.sh
	echo -e "\e[1;34m--HSOSTS 广告屏蔽脚本卸载完毕,返回主菜单--\e[0m\n" && logger " HSOSTS 广告屏蔽脚本卸载完成..." && sleep 3
	sh /tmp/Ad_Install
fi

if [ "$Function_options" == "6" ]; then
	if [ ! -d "/tmp/dns.sh" ]; then
		wget --no-check-certificate https://raw.githubusercontent.com/896660689/AD/master/Other/Dns.sh -O /tmp/dns.sh;sh /tmp/dns.sh
	else
		chmod +x /tmp/dns.sh && sh /tmp/dns.sh
		echo -e "\e[1;34m 存在Dns文件,开始安装 \e[0m\n" && sleep 3
	fi
	[ -f /tmp/dns.sh ] && rm -f /tmp/dns.sh
	echo -e "\e[1;34m DNS 环境配置完成，返回主菜单 \e[0m\n" && logger " DNS 环境配置完成..." && sleep 3
	sh /tmp/Ad_Install
fi

if [ "$Function_options" == "7" ]; then
	if [ -f "/etc/storage/dnsmasq/dnsmasq.conf" ]; then
		echo -e "\e[1;31m 开始卸载启动规则 \e[0m\n"
		sed -i '/127.0.0.1/d' /etc/storage/dnsmasq/dnsmasq.conf
		sed -i '/log/d' /etc/storage/dnsmasq/dnsmasq.conf
		#sed -i '/3600/d' /etc/storage/dnsmasq/dnsmasq.conf
		#sed -i '/conf-dir/d' /etc/storage/dnsmasq/dnsmasq.conf
		if [ -f "/etc/storage/dnsmasq.d/resolv_bak" ]; then
			cp -f /etc/storage/dnsmasq.d/resolv_bak /etc/resolv.conf
		fi
	fi

	if [ -d "/etc/storage/dnsmasq.d/hosts" ]; then
		echo -e "\e[1;31m 删除残留文件夹以及配置 \e[0m\n" && sleep 2
		rm -rf /etc/storage/dnsmasq.d
	fi

	if [ -f "/etc/storage/post_iptables_script.sh" ]; then
		echo -e "\e[1;31m 删除防火墙规则 \e[0m\n" && sleep 2
		sed -i '/DNAT/d' /etc/storage/post_iptables_script.sh
		sed -i '/iptables-save/d' /etc/storage/post_iptables_script.sh
		sed -i '/resolv.conf/d' /etc/storage/post_iptables_script.sh
		sed -i '/restart_dhcpd/d' /etc/storage/post_iptables_script.sh
	fi
	grep "dnsmasq.log" /etc/storage/cron/crontabs/`nvram get http_username`
	if [ $? -eq 0 ]; then
		sed -i '/dnsmasq.log/d' /etc/storage/cron/crontabs/`nvram get http_username`
	fi
	
	if [ -f "/usr/sbin/dnsmasq" ]; then
		echo -e "\e[1;31m 重启 dnsmasq \e[0m\n"
		restart_dhcpd && /usr/sbin/dnsmasq restart >/dev/null 2>&1
	fi
	echo -e "\e[1;34m-- Hsfq 卸载完毕,返回主菜单--\e[0m\n" && logger " DNS 环境配置完成..." && sleep 3
	sh /tmp/Ad_Install
fi

if [ "$Function_options" == "8" ]; then
	echo
	[ -f /tmp/hsfq_script.sh ] && rm -rf /tmp/hsfq_script.sh
	wget --no-check-certificate https://raw.githubusercontent.com/896660689/AD/master/Other/FHQ_ZQ -O \
	/tmp/fhq_zq && chmod +x /tmp/fhq_zq && sh /tmp/fhq_zq
	echo -e "\e[1;36m 完成 padavan 防火墙增强规则 \e[0m" && logger "padavan 防火墙规则,添加完成..." && sleep 3 
	sh /tmp/Ad_Install
fi

if [ "$Function_options" == "0" ]; then
	echo -e "*****************************************************"
	echo -e "*                   Time:`date +'%Y-%m-%d'`                    *"
	echo -e "*****************************************************\n"
	[ -f /tmp/ad_an ] && rm -f /tmp/ad_an;[ -f /tmp/ad_up ] && rm -f /tmp/ad_up;[ -f /tmp/ad_stop ] && rm -f /tmp/ad_stop
	[ -f /tmp/7620n.tar.gz ] && rm -f /tmp/7620n.tar.gz;[ -f /tmp/Ad_Install ] && rm -f /tmp/Ad_Install
fi
