#!/bin/sh
# Compile:by-lanse	2019-1-9

route_vlan=`/sbin/ifconfig br0 |grep "inet addr"| cut -f 2 -d ":"|cut -f 1 -d " " `
Firewall_rules="/etc/storage/post_iptables_script.sh"

"$Firewall_rules"

if [ -f "$Firewall_rules" ]; then
	echo -e "\e[1;36m 添加防火墙增强代码 \e[0m\n"
	sed -i '/DNAT/d' /etc/storage/post_iptables_script.sh
	sed -i '/iptables-save/d' /etc/storage/post_iptables_script.sh
	sed -i '$a /bin/iptables-save' /etc/storage/post_iptables_script.sh
fi
echo "/bin/iptables -t nat -A PREROUTING -p tcp --dport 53 -j DNAT --to $route_vlan" >> /etc/storage/post_iptables_script.sh
echo "/bin/iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to $route_vlan" >> /etc/storage/post_iptables_script.sh
if [ -f "/etc/storage/post_iptables_script.sh" ]; then
	sed -i '/resolv.conf/d' /etc/storage/post_iptables_script.sh
	sed -i '/restart_dhcpd/d' /etc/storage/post_iptables_script.sh
	sed -i '$a cp -f /etc/storage/dnsmasq.d/resolv.conf /tmp/resolv.conf' /etc/storage/post_iptables_script.sh
	sed -i '$a sed -i "/#/d" /tmp/resolv.conf;mv -f /tmp/resolv.conf /etc/resolv.conf' /etc/storage/post_iptables_script.sh
	sed -i '$a restart_dhcpd' /etc/storage/post_iptables_script.sh
fi
