#!/bin/sh
# Compile:by-lanse	2019-1-9

route_vlan=`/sbin/ifconfig br0 |grep "inet addr"| cut -f 2 -d ":"|cut -f 1 -d " " `
Firewall_rules="/etc/storage/post_iptables_script.sh"

echo -e "\e[1;36m 安装防火墙增强规则 \e[0m"
if [ -f "$Firewall_rules" ]; then
	
	echo -e "\e[1;36m 已经存在增强规则 \e[0m"
	
else
	sed -i '/iptables-save/d' "$Firewall_rules"
	sed -i '/iptables-save/d' "$Firewall_rules"
	sed -i '/iptables-save/d' "$Firewall_rules"
	sed -i '/iptables-save/d' "$Firewall_rules"
	
	echo "iptables -I FORWARD -p tcp --syn -d $route_vlan -j DROP" >> "$Firewall_rules"
	echo "iptables -I FORWARD -p tcp --syn -d $route_vlan -m limit --limit 2/s --limit-burst 5 -j ACCEPT" >> "$Firewall_rules"
	
	echo "iptables -I FORWARD -p tcp --tcp-flags SYN,ACK,FIN,RST RST -d $route_vlan -j DROP" >> "$Firewall_rules"
	echo "iptables -I FORWARD -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s -d $route_vlan -j ACCEPT" >> "$Firewall_rules"
	echo "iptables -I FORWARD -p icmp --icmp-type echo-request -d $route_vlan -j DROP" >> "$Firewall_rules"
	echo "iptables -I FORWARD -p icmp --icmp-type echo-request -m limit --limit 2/s -d $route_vlan -j ACCEPT" >> "$Firewall_rules"


	sed -i '$a cp -f /etc/storage/dnsmasq.d/resolv.conf /tmp/resolv.conf' /etc/storage/post_iptables_script.sh
	sed -i '$a sed -i "/#/d" /tmp/resolv.conf;mv -f /tmp/resolv.conf /etc/resolv.conf' /etc/storage/post_iptables_script.sh
	sed -i '$a restart_dhcpd' /etc/storage/post_iptables_script.sh
fi
