#!/bin/sh
## Adaptation Grassland in Lucheng 2019.01.10

LOGTIME=$(date "+%H:%M:%S")
LOGFILE=/var/log/adbyby_watchdog.log
Ad_Home="/tmp/adb"
max_log_bytes=6000

touch $LOGFILE
while true; do
	loger(){
		[ -f $LOGFILE ] && [ $(stat -c %s $LOGFILE) -gt $max_log_bytes ] && rm -f $LOGFILE
		time=$(date "+%H:%M:%S")
		echo "$time adbyby_watchdog $1" >> $LOGFILE
	}
	while [ ! -f /tmp/cron_adb.lock ]
	do
		CPULoad=`uptime |sed -e 's/\ *//g' -e 's/.*://g' -e 's/,.*//g' -e 's/\..*//g'`
		while [ $((CPULoad)) -ge "2" ]
		do
			touch /tmp/cron_adb.lock
			port=$(iptables -t nat -L | grep 'ports 8118' | wc -l)
			loger " adbyby 找到$port个8118透明代理端口,正在关闭..."
			while [[ "$port" -ge 1 ]]
			do
				iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
				port=$(iptables -t nat -L | grep 'ports 8118' | wc -l)
			done
			logger " CPU 负载拥堵,关闭 adbyby 程序,关闭 8118 代理端口..."
			loger "【$LOGTIME】"" adbyby 已关闭全部8118透明代理端口..."
			killall adbyby
			sed -i '/adb/d' /etc/storage/post_wan_script.sh
			loger "【$LOGTIME】"" adbyby 进程已成功关闭..."
		done
		processor=`cat /proc/cpuinfo| grep "processor"| wc -l`
		processor=`expr $processor \* 2`
		while [[ "$CPULoad" -gt "$processor" ]] 
		do
			CPULoad=`uptime |sed -e 's/\ *//g' -e 's/.*://g' -e 's/,.*//g' -e 's/\..*//g'`
		done
		loger "【$LOGTIME】"" adbyby CPU 负载正常..."
		rm -f /tmp/cron_adb. lock
	done
	PIDS=$(ps |grep "$Ad_Home/bin/adbyby" |grep -v "grep" |wc -l)
	while [ $PIDS -eq 0 ]
	do
		logger "注意: adbyby 意外关闭,将重启 adbyby!"
		[ -f $Ad_Home/bin/adbyby ] && $Ad_Home/bin/adbyby.sh
		loger "【$LOGTIME】""注意:TMP: adbyby 意外关闭,将重启 adbyby!"
		iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
		exit 0
	done
	while [ $PIDS -gt 6 ]
	do
		loger "【$LOGTIME】""注意:发现 adbyby 多于6个进程,将重启 adbyby!"
		ps |grep "$Ad_Home/bin/adbyby" | grep -v 'grep' | awk '{print $1}' |xargs kill -9
		logger "注意: adbyby 多于6个进程,将重启 adbyby!" && /tmp/adb/bin/adbyby.sh
		iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
		exit 0
	done
	port=$(iptables -t nat -L | grep "tcp dpt:www redir ports 8118" | wc -l)
	while [ $port -eq 0 ]
	do
		loger "【$LOGTIME】""注意: adbyby 防火墙转发规则丢失,将添加规则!"
		iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
		logger "注意: adbyby 防火墙转发规则丢失,将添加规则"
	done
	while [ $port -gt 1 ]
	do
		loger "【$LOGTIME】""注意:发现 adbyby 多条防火墙转发规则,将删除多余规则!"
		iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
		logger "注意:发现 adbyby 多条防火墙转发规则,将删除多余规则!"
		port=$(iptables -t nat -L | grep "tcp dpt:www redir ports 8118" | wc -l)
	done
	sleep 60
done
