#!/bin/sh
## Adaptation Grassland in Lucheng 2019.01.10

username=`nvram get http_username`
ad_home="/tmp/adb"
Firewall_rules="/etc/storage/post_iptables_script.sh"
Run_script="/etc/storage/post_wan_script.sh"

if [ -d "$ad_home" ]; then
	echo -e "\e[1;31m 关闭 adbyby 进程，代理端口任务 \e[0m"
	/tmp/adb/bin/stopadb; sleep 3
	logger "关闭 adbyby 进程，代理端口任务。"
	grep -q "adb" /etc/storage/cron/crontabs/$username
	if [ "$?" -eq "0" ]
	then
		sed -i '/adb/d' /etc/storage/cron/crontabs/$username
	fi
	grep "adb" $Run_script
	if [ $? -eq 0 ]
	then
		sed -i '/adb/d' $Run_script
	fi
	restart_dhcpd && echo "adbyby 卸载完成" && logger "adbyby 已卸载完成...。"
else
	echo "adbyby 没有发现安装程序" && logger "adbyby 没有v发现安装程序..."
	if [ -n "`pidof adbyby`" ] ; then
		kill -9 "`pidof adbyby`"
	fi
	while [ -n "`pidof ad_gz`" ] ; do
		kill -9 "`pidof ad_gz`"
	done
	sleep 3
	if [ -f "$ad_home/bin/adbyby" ]; then
		port=$(iptables -t nat -L |grep 'ports 8118' |wc -l)
		logger "adbyby" "找到$port个8118透明代理端口，正在关闭。"
		while [[ "$port" -ge 1 ]]
		do
			iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
		done
		echo -e "\e[1;31m 关闭 adbyby 进程，代理端口任务 \e[0m"
	fi
	grep -q "adb" /etc/storage/cron/crontabs/$username
	if [ "$?" -eq "0" ]
	then
		sed -i '/adb/d' /etc/storage/cron/crontabs/$username
	fi
	grep "adb" $Run_script
	if [ $? -eq 0 ]
	then
		sed -i '/adb/d' $Run_script
	fi
	restart_dhcpd && sleep 3 && echo -e "\e[1;31m adbyby 卸载完成... \e[0m"
fi
[ -f /var/log/adbyby_watchdog.log ] && rm -f /var/log/adbyby_watchdog.log
[ -d /tmp/adb ] && rm -R /tmp/adb; sleep 3;[ -f /tmp/cron_adb.lock ] && rm -f /tmp/cron_adb.lock
[ ! -d "$ad_homea" ] && exit 0
